name: Run Pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    # install fio io tools 
    - name: Install fio
      run: |
        sudo apt-get update
        sudo apt-get install fio
    

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

